AllCops:
  Exclude:
    - 'Guardfile'
    - 'bin/*'
    - 'config/initializers/backtrace_silencers.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 15
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
